spring:
  application:
    name: member-service
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:10418}
  cloud:
    config:
      username: be12-team1
      password: nhnacademy123!

server:
  port: ${SERVER_PORT}

# 유레카 클라이언트 비활성화 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
