spring:
  application:
    name: MemberApi
  profiles:
    active: dev, env
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
      #hibernate:
    #ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalajsfhalsjfhkqjknvazxv
  security:
    oauth2:
      client:
        registration:
          # 구글
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email
          # PAYCO
          payco:
            client-id: ${PAYCO_CLIENT_ID}
            client-secret: ${PAYCO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/payco"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: public
            client-name: Payco

        provider:
          # PAYCO provider 엔드포인트
          payco:
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            # 사용자 정보 조회 URL (문서 기준 URL로 설정)
            user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
            user-name-attribute: header # Payco의 응답 구조를 파싱하기 위한 기준 속성



server:
  port: ${SERVER_PORT}

# 유레카 클라이언트 비활성화 설정
eureka:
  client:
    enabled: false

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_URL}
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
#      springframework:
#        transaction:
#          interceptor: trace
#    com:
#      nhnacademy:
#        OrderApplication: DEBUG
