spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: shhk2100@gmail.com
    password: ${SMTP-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 인증 필요한 경우 true로 지정한다. Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정
          starttls: # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정한다. TLS는 데이터를 암호화하여 안전한 전송을 보장하는 프로토콜
            enable: true
            required: true
          connectiontimeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간(ms). 연결이 불안정한 경우 대기 시간이 길어질 수 있기 때문에 너무 크게 설정하면 전송 속도가 느려질 수 있음
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간(ms). 서버에서 응답이 오지 않는 경우의 대기 시간을 제한하려고
          writetimeout: 5000 # 클라이언트가 작업을 완료하는 데 대기해야 하는 시간(ms). 이메일을 SMTP 서버로 전송하는 데 걸리는 시간을 제한
          auth-code-expiration-millis: 1800000  # 이메일 인증 코드 만료 시간(ms). 30 * 60 * 1000 == 30분
