server:
  port: 10403

spring:
  application:
    name: member-service
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    #hibernate:
    #ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      # JPA - H2 Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalajsfhalsjfhkqjknvazxxv

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email
  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:test;MODE=MySQL
    url: jdbc:h2:mem:test
    username: test
    password: 1234


  mail:
    host: smtp.gmail.com
    port: 587
    username: shhk2100@gmail.com
    password: ${SMTP-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 인증 필요한 경우 true로 지정한다. Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정
          starttls: # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정한다. TLS는 데이터를 암호화하여 안전한 전송을 보장하는 프로토콜
            enable: true
            required: true
          connectiontimeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간(ms). 연결이 불안정한 경우 대기 시간이 길어질 수 있기 때문에 너무 크게 설정하면 전송 속도가 느려질 수 있음
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간(ms). 서버에서 응답이 오지 않는 경우의 대기 시간을 제한하려고
          writetimeout: 5000 # 클라이언트가 작업을 완료하는 데 대기해야 하는 시간(ms). 이메일을 SMTP 서버로 전송하는 데 걸리는 시간을 제한
          auth-code-expiration-millis: 1800000  # 이메일 인증 코드 만료 시간(ms). 30 * 60 * 1000 == 30분


  # H2 Console (http://localhost:8080/h2-console)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  #config 클라이언트 비활성화
  cloud:
    config:
      enabled: false

# 유레카 클라이언트 비활성화 설정
eureka:
  client:
    enabled: false





  # -------------------------------------------------
  # MySQL Database
  # -------------------------------------------------
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   ## internal IP
  #   # url: jdbc:mysql://10.116.64.14:13306/nhn_academy_12?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
  #   ## external IP
  #   url: jdbc:mysql://220.67.216.14:13306/nhn_academy_12?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
  #   username: nhn_academy_12
  #   password: ${DB_PASSWORD}
  #
  # jpa:
  #   database-platform: org.hibernate.dialect.MySQLDialect
  #   hibernate:
  #     ddl-auto: validated